### ISSUE TITLE
walk generate problem

### ISSUE THREAD

**Issue by generalfei** [jhljx/CTGCN#2]
I want to know that sometimes the programe can generate walk pairs, sometimes it can't as the walk pairs floder has nothing. The programe can't call the function helper.random_walk.

**Comment by jhljx** [comment]
Hi! If you want to call the function 'helper.random_walk', you could first compile this file. The commands are:

    cd preprocessing    
    python3 setup.py build_ext --inplace

If you have finished this compilation step, you will find a helper.so file under the preprocessing directory. Then you run the 'preprocessing/\_\_init\_\_.py' file, you could call the program to generate walk pairs. 

Another attept is that you create a new python file, and paste the code in 'helper.pyx' file into this new python file. Then you modify this file to fix errors and modify the statement in 'preprocessing/walk_generation.py' to call new random_walk function in your new created file.

**Comment by generalfei** [comment]
@jhljx 
Thanks for your reply.  Previously I use the first method and it does not work. Now I fix the problem by using the second method.
Another problem  is that some error happened when I run the evolvegcn method with "enron" dataset. It was "list index out of range" error.  The error comes from egcn.py, line 48.
```
    Traceback (most recent call last):
  File "train.py", line 498, in <module>
    evolvegcn_embedding(dataset=dataset)
  File "train.py", line 185, in evolvegcn_embedding
    evolvegcn.learn_embedding(adj_list, x_list, epoch=5, batch_size=4096 * 8, lr=0.001, start_idx=idx, weight_decay=5e-4, model_file='evolvegcnh', export=True)
  File "../CTGCN/embedding.py", line 346, in learn_embedding
    embedding_list = model(x_list, adj_list)
  File "/data/jsf/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "../CTGCN/baseline/egcn.py", line 26, in forward
    Nodes_list = unit(A_list, Nodes_list, nodes_mask_list)
  File "/data/jsf/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "../CTGCN/baseline/egcn.py", line 48, in forward
    node_embs = node_embs_list[t]
IndexError: list index out of range
```
I try some other dataset, and the same problem happens.

**Comment by jhljx** [comment]
Well, I think I encountered this problem before. The reason of the error might be that the shape of input 'x_list' is not correct. You could print the shape of input 'adj_list' and 'x_list' and check it. If you want to produce dynamic node embeddings, the length of 'adj_list' and 'x_list' would be T, which is the number of timestamps.

An example is that:

                        t=1                  t=2
    adj_list = [N * N sparse tensor, N * N sparse tensor]
    x_list = [N * m feature tensor, N * m feature tensor]

Or you could just print the shape of 'node_embs_list' just before the statement 'node_embs = node_embs_list[t]' in 'egcn.py' file.

**Comment by jhljx** [comment]
Let me check this code.

generalfei <notifications@github.com> 于2020年6月9日周二 上午11:46写道：

**Comment by jhljx** [comment]
I've already fixed the errors in 'get_degree_feature_list' function in 'embedding.py' file. Please try agin and thanks for pointing out this problem!

**Comment by generalfei** [comment]
@jhljx 
Thanks for your reply. Now the program can run without error.
And I have some other questions to confirm.
1. The output of dynamic methods like evolvegcn and CTGCN contains several csv files, and each file  represents the embedding result of the corresponding timestamp. And the number of rows in each file equals to the number of nodes in the whole dynamic network. Is that right？
2.  The loss of the evolvegcn seems unnormal in the datasets you provide, which is too large. And the training speed seems too fast in large networks like enron. I only change the lr to 1e-5. Have you ever meet these situations before?
```
epoch 1 , batch num =  1 , loss: 2729788160.0 , cost time:  2.5932819843292236  seconds!
epoch 1 , batch num =  2 , loss: 44189.1328125 , cost time:  2.525237560272217  seconds!
epoch 1 , batch num =  3 , loss: 3935442944.0 , cost time:  2.3210995197296143  seconds!
epoch 2 , batch num =  1 , loss: 1353334656.0 , cost time:  2.60317325592041  seconds!
epoch 2 , batch num =  2 , loss: 845377024.0 , cost time:  2.4942543506622314  seconds!
epoch 2 , batch num =  3 , loss: 0.0 , cost time:  1.0476868152618408  seconds!
epoch 3 , batch num =  1 , loss: 537975808.0 , cost time:  2.5916409492492676  seconds!
epoch 3 , batch num =  2 , loss: 17172.869140625 , cost time:  2.4934446811676025  seconds!
epoch 3 , batch num =  3 , loss: 0.0 , cost time:  1.0323877334594727  seconds!
epoch 4 , batch num =  1 , loss: 38967404.0 , cost time:  2.6370625495910645  seconds!
```
Hope for your reply. Thanks a lot.

**Comment by jhljx** [comment]
Well, great! I'm happy to see you can run these programs smoothly! Here is the answer to your questions.
1. For this question, I assume dynamic graphs of all timestamps share the same node set. So the output embedding file of each timestamp contains N rows, which corresponds to each node in node list. The order of node is the same as that in the 'data/**/nodes_set/nodes.csv'. And the column number is the same as the embedding dimension.

2. Well, the loss shown above is a bit abnormal and I've already encountered this situation before. But I found it seemed that this situation didn't matter to the final evaluation results. By the way, I think the reason why evolvegcn is fast is that: 
    **a.** the input feature dimension of evolvegcn is almost 100~500, and one-hot feature matrix couldn't be used for evolvegcn. So evolvegcn has fewer parameters than those models which use one-hot feature matrix as input. 
    **b.** evolvegcn shares the parameters in gcn weights across all timestamps, which also saves a lot of parameters. But if CTGCN uses same parameters across different timestamps, it would perform poorly. 
    Overall, evolvegcn is an efficient baseline method. When I run experiments, evolvegcn can run quit fast.

**Comment by generalfei** [comment]
@jhljx 
Ok. Thanks. You have help me a lot.
One more thing is that, on large networks like enron, the ctgcn_connective method costs a lot of CUDA memory. My machine has 22G gpu memory, which is not enough. I change the embdding size and batch size but it doesn't help. Any hyperparameter else to change?

**Comment by jhljx** [comment]
Well, this is a problem. I tested CTGCN before, and found that its gpu version costed too much memory on large graph data sets. This is actually a limitation of CTGCN. 

So I tried another way to solve this problem. I used its cpu version to generate node embeddings. But it would be a bit slower than gpu version. If you have 22G gpu, I think your main memory is enough to run cpu version of CTGCN. Hope this alternative solution helps you.

**Comment by jhljx** [comment]
I also tested different hyper-parameters, and the hyper-parameter sensitive analysis results can be found in [our paper](https://arxiv.org/pdf/2003.09902.pdf). 

> As for the proposed method, CTGCN-C has a linear layer and 2 CGCLs in each CGCN, while CTGCN-S has a 3-layer MLP and a CGCL in each CGCN. We adopt Adam optimizer with learning rate as 0.001 and weight decay as 5 × 10^−4 in this work.

**It's not necessary to change the layer numbers of CTGCN as shown above**, because this layer architecture can highly affect the performance. And if you really want to tune hyper-parameters, you can tune learning rate 'lr', embedding dimension 'd', and negative sampling weight 'Q'. Actually, CTGCN is robust to hyper-parameters. If you don't tune these hyper-parameters, I think it's also ok.

**Comment by jhljx** [comment]
Hi, there.
The code of random walk has some bugs. And I make this project private temporally to modify some code. If you are still using the code. You can change the code in helper.pyx as shown bellow

    for i in range(seq_len):
        for j in range(i + 1, seq_len):
            if walk[i] == walk[j]:
                continue
            from_id, to_id = walk[i], walk[j]
            walk_spadj[i, j] = 1
            walk_spadj[j, i] = 1
            node_freq_arr[from_id] += 1
            node_freq_arr[to_id] += 1

to:

    for i in range(seq_len):
        for j in range(i + 1, seq_len):
            if walk[i] == walk[j]:
                continue
            from_id, to_id = walk[i], walk[j]
            walk_spadj[from_id, to_id] = 1
            walk_spadj[to_id, from_id] = 1
            node_freq_arr[from_id] += 1
            node_freq_arr[to_id] += 1

**Comment by jhljx** [comment]
And this bug results in the strange loss of CGCN, making loss in some epoch become 0.
