### ISSUE TITLE
Question About core_num

### ISSUE THREAD

**Issue by icecity96** [jhljx/CTGCN#6]
It seems you always use 1-core adj?

Since all your `CoreDiffusion` layers use `core_num` default value 1..
```python
CoreDiffusion(input_dim, output_dim, bias=bias, rnn_type=rnn_type)
```

If so, how k-core works?

**Comment by jhljx** [comment]
the parameter 'core_num' is unused in CoreDiffusion Layer. So the k-core adj and embedding list is passed as the parameter of model forward function.
