### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by MiladInk** [jhljx/CTGCN#7]
Hi! Thanks for the great repository. I am using your approach to do link prediction on a dataset and this dataset has a lot of nodes, it has near 60000 nodes and 4 million edges. However, I cannot run your approach or other approaches like DynGEM or VGRNN on this dataset because it ran into CUDA OOM. The only approaches which worked for me from this repository are the GCRN and TIMERS.

I am wondering whether there is something I can tune in the config files so I can run the code successfully on my gpu without CUDA OOM. I have tried reducing the `hidden_dims` and `batch_size` but no luck. It seems not to change anything at all. I even tried `batch_size` of 1 and `hidden_dims` of 1. 

Would you mind giving me some suggestions about that?

Thanks a lot in advance!

**Comment by CLaniakea** [comment]
I tried this code on my data and it did not work on large graph data. I found that batch_size is not useful for the OOM problem as the model will calculate all nodes at a time but only one batch of data loss. You can use a smaller hidden_dim or emb_dim. do you have a better solution?

**Comment by jhljx** [comment]
Most of these methods could not support large graphs(nodes over 30000). One possible solution is to use message-passing architecture, rather than use matrix-multiplication for graph diffusion process.
